[package]
name = "maprs3d"
version = "0.1.0"
edition = "2021"
authors = ["shadymeowy"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
time = "0.3.28"
